### ISSUE TITLE
Goofy AF Terminology

### ISSUE THREAD

**Issue by El-Qassam** [MrWaltz-b14/ransomware-V2#1]
Let me fix your goofy AF terms. First of all, I believe this could actually work on Linux (if not all other OS’), because C:// is just the central hard drive, it doesn’t change unless you change its term (hence why a USB is E:// — at least 99% of the time), and if you have Linux on the hard drive or RAM (not a USB) then this would make no difference, although it would access the (unshowed — if you are on Linux) files in the Windows partition.

Second of all, McAffee beat the living daylights out of this. Not only did even my Rasberry Pi block it, but it wouldn’t even let me download it (I had to uninstall both Norton and McAffee entirely). Try changing file names into more stealthy thingies.

Lastly, you make fun of my formatting while yours is dog.

Overall Rating: PooPoo/10

**Comment by MrWaltz-b14** [comment]
Okay nerd! First Linux does not have any C: or E: drive. Secondly it’s still in the making and is only a Beta version, third FORMATTING IS HOT.

**Comment by MrWaltz-b14** [comment]
Formatting is actually perfect according to pycharm which is a professional software for python dev.

**Comment by El-Qassam** [comment]
As for the drive paths, I forgot that Linux uses like /dev I think. But still.

**Comment by El-Qassam** [comment]
C and E are pretty standard. Let the user find out for themselves. Formatting is still dog.

**Comment by MrWaltz-b14** [comment]
pycharm and VSC have modules you can install that help with formatting. pycharm which is a very popular and professionally recognized IDE also has one of these that is pre installed.

**Comment by MrWaltz-b14** [comment]
on top of this, the reason any anti malware will destory this is because it is a python file. if it were converted to a .exe windows defender would recognize it as a developer of sorts and assume that you trust them. of course things that put the virus in a vm for like 1 minute would quickly realize.

**Comment by El-Qassam** [comment]
Agreed
